# pHD
# This file must contain valid YAML code. A YAML checker may be found at http://www.yamllint.com
#
# pHD is an add-on for hologram providers:
# - DecentHolograms       https://www.spigotmc.org/resources/96927/
# - HolographicDisplays   https://dev.bukkit.org/projects/holographic-displays
#
# Design: SlimeDog
# Implementation: drives_a_ford
# Testing: SlimeDog
#
# Supported MC versions:
# https://github.com/SlimeDog/pHD/wiki/Technical-Details
# Default configuration:
# https://github.com/SlimeDog/pHD/master/src/main/resources/config.yml

# ========== DEFAULT PARAMETER VALUES ==============================================================
# If parameter values are not specified, the default values will be used.
# Activation-distance: The distance at which a hologram may be seen.
# Show-time: The time a hologram will be displayed, in seconds.
defaults:
  activation-distance: 20
  show-time: 15

# ========== SAVE FREQUENCY ========================================================================
# For NTIMES holograms, how frequently player view data are saved to the database, in seconds.
# The data should not be saved too frequently, for performance reasons.
save-frequency: 60

# ========== DATA STORAGE TYPE =====================================================================
# Data storage may be either SQLITE or YAML. SQLITE performs better, so is the default.
storage-type: SQLITE

# ========== CHECK FOR UPDATES =====================================================================
# If you do not want notification of available updates in the console log, you may disable it here.
check-for-updates: true
# Update source may be either Hangar (default) or SpigotMC.
update-source: Hangar

# ========== BSTATS METRICS ========================================================================
# By default, the plugin collects and transmits anonymous statistics to bstats.org.
# Data collection may be disabled here, or generally in the bStats/config.yml.
enable-metrics: true

# ========== DEBUG MODE ============================================================================
# This will print a large amount of debugging information to the console/log.
# Recommendation: Leave this false unless specifically requested by the pHD support team.
debug: false
