# pHD
# This file must contain valid YAML code. A YAML checker may be found at http://www.yamllint.com
#
# pHD is an add-on for HolographicDisplays
# https://dev.bukkit.org/projects/holographic-displays
#
# Design: SlimeDog
# Implementation: drives_a_ford
# Testing: SlimeDog
#
# Spigot version support: 1.13.2, 1.14.4, 1.15.x
#
defaults:
  activation-distance: 20
  show-time: 10
save-delay: 60 # in seconds
storage-type: SQLITE # or YAML
enable-metrics: true
check-for-updates: false
