# pHD
#
# See http://wiki.bukkit.org/Plugin_YAML for a complete list of requirements and options.

name: ${project.name}
version: ${project.version}
api-version: 1.18
main: ${project.groupId}.${project.artifactId}.PeriodicHolographicDisplays
description: ${project.description}
website: ${website}
authors: [drives_a_ford, SlimeDog]
depend: [HolographicDisplays, ProtocolLib]
softdepend: [Citizens, LuckPerms, Multiverse-Core, MultiWorld]

commands:
  phd:
    description: See plugin help
    usage: /<command>
    permission: phd.use
  phd help:      
    description: See plugin help
    usage: /<command>
    permission: phd.use
  phd list:
    description: List pHD holograms
    usage: /<command> [<type>]
    permission: phd.list
  phd info:
    description: See info about a pHD hologram
    usage: /<command> <hologram> <type>
    permission: phd.info
  phd report:
    description: See how many times a player has viewed holograms
    usage: /<command> NTIMES <player>
    permission: phd.report
  phd manage:
    description: Manage an HD hologram with pHD
    usage: /<command> <hologram> <type> <options>
    permission: phd.manage
  phd set:
    description: Set attributes of a pHD hologram
    usage: /<command> <hologram> <type> <options>
    permission: phd.set
  phd unset:
    description: Unset attributes of a pHD hologram
    usage: /<command> <hologram> <type> <options>
    permission: phd.unset
  phd unmanage:
    description: Unmanage an HD hologram with pHD
    usage: /<command> <hologram> <type>
    permission: phd.unmanage
  phd reload:
    description: Reload the configuration and data
    usage: /<command>
    permission: phd.reload
  phd convert:
    description: Convert data between storage types
    usage: /<command> <sourceStorageType> <targetStorageType>
    permission: phd.convert

permissions:
  phd.*:
    description: All phd permissions
    default: op
    children:
      phd.use: true
      phd.list: true
      phd.info: true
      phd.report: true
      phd.manage: true
      phd.set: true
      phd.unset: true
      phd.unmanage: true
      phd.reload: true
      phd.convert: true
  phd.use:
    description: Allows use of the phd command
    default: op
  phd.list:
    description: Allows listing pHD holograms
    default: op
  phd.info:
    description: Allows listing attributes of specified hologram
    default: op
  phd.report:
    description: Allows listing number of times a player has seen an NTIMES hologram
    default: op
  phd.manage:
    description: Allows pHD management of a HolographicDisplays hologram
    default: op
  phd.set:
    description: Allows setting attributes of a hologram
    default: op
  phd.unset:
    description: Allows removing attributes of a hologram
    default: op
  phd.unmanage:
    description: Allows removing pHD management of a hologram
    default: op
  phd.reload:
    description: Allows reloading the configuration, messages, and data
    default: op
  phd.convert:
    description: Allows converting between different storage types
    default: op
