# pHD
#
# See http://wiki.bukkit.org/Plugin_YAML for a complete list of requirements and options.

name: ${project.name}
version: ${project.version}
api-version: 1.13
main: ${project.groupId}.${project.artifactId}.PeriodicHolographicDisplays
description: ${project.description}
authors: [SlimeDog, drives_a_ford]
depend: [HolographicDisplays]
softdepend: [Citizens, LuckPerms, Multiverse-Core, MultiWorld]

commands:
  phd:
    description: Main command
    usage: /<command> <subcommand> <parameters>
    permission: phd.use
  phd info <name> <type>:
    description: See info about a pHD hologram
    usage: /<command> <subcommand> <parameters>
    permission: phd.info
  phd report NTIMES <name>:
    description: See how many times a player has viewed a NTIMES hologram
    usage: /<command> <subcommand> <parameters>
    permission: phd.report
  phd list:
    description: List pHD holograms
    usage: /<command> <subcommand> <parameters>
    permission: phd.list
  phd manage <name> <type> <params...>:
    description: Manage a hologram as a pHD hologram
    usage: /<command> <subcommand> <parameters>
    permission: phd.manage
  phd set <name> <type> <params...>:
    description: Set a parameter of a pHD hologram
    usage: /<command> <subcommand> <parameters>
    permission: phd.set
  phd unset <name> <type> <params...>:
    description: Unset a parameter of a pHD hologram
    usage: /<command> <subcommand> <parameters>
    permission: phd.unset
  phd unmanage <name> <type>:
    description: Unmanage
    usage: /<command> <subcommand> <parameters>
    permission: phd.unmanage
  phd reload:
    description: Reload the config and the holograms
    usage: /<command>
    permission: phd.reload
  phd convert <sourceStorageType> <targetStorageType> [--force]:
    description: Convert storage from source storage to target storage
    usage: /<command> <subcommand> <parameters>
    permission: phd.convert

permissions:
  phd.*:
    description: All phd permissions
    default: op
    children:
      phd.use: true
      phd.info: true
      phd.report: true
      phd.list: true
      phd.manage: true
      phd.set: true
      phd.unset: true
      phd.unmanage: true
      phd.reload: true
      phd.convert: true
  phd.use:
    description: Allows using the phd command
    default: op
  phd.list:
    description: Allows listing of pHD holograms
    default: op
  phd.info:
    description: Allows listing of attributes of specified hologram
    default: op
  phd.report:
    description: Allows listing of player seen times for NTIMES hologram
    default: op
  phd.manage:
    description: Allows managing a HolographicDisplays hologram
    default: op
  phd.set:
    description: Allows setting a parameter of a hologram
    default: op
  phd.unset:
    description: Allows setting a parameter of a hologram to its default
    default: op
  phd.unmanage:
    description: Allows dropping all pHD parameters of a hologram
    default: op
  phd.reload:
    description: Allows reloading the config
    default: op
  phd.convert:
    description: Allows converting from different types of storage
    default: op
