# pHD
#
# See http://wiki.bukkit.org/Plugin_YAML for a complete list of requirements and options.

name: ${project.name}
version: ${project.version}
api-version: 1.13
main: ${project.groupId}.${project.artifactId}.PeriodicHolographicDisplays
description: ${project.description}
authors: [SlimeDog, drives_a_ford]
softdepend: [LuckPerms]
depend: [HolographicDisplays]

commands:
  phd:
    description: Main command
    usage: /<command> <subcommand> args
    permission: phd.command.phd

permissions:
  phd.*:
    description: All phd permissions
    default: op
    children:
      phd.list: true
      phd.info: true
      phd.set: true
      phd.unset: true
      phd.unmanage: true
      phd.reload: true
  phd.list:
    description: Allows listing of pHD holograms
    default: op
  phd.info:
    description: Allows listing of attributes of specified hologram
    default: op
  phd.manage:
    description: Allows managing a HolographicDisplays hologram
    default: op
  phd.set:
    description: Allows setting a parameter of a hologram
    default: op
  phd.unset:
    description: Allows setting a parameter of a hologram to its default
    default: op
  phd.unmanage:
    description: Allows dropping all pHD parameters of a hologram
    default: op
  phd.reload:
    description: Allows reloading the config
    default: op
